import Head from "next/head";
import Navbar from "../components/Navbar";
import Cover from "../components/Cover";
import Chat from "../components/subcontents/Chat";
import Login from "../components/Login";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Cover />
        <Chat />
        <Login />
      </main>
    </div>
  );
}
